= Spring Data for Apache Cassandra example in Kotlin

The purpose of this example is to serve as a quick reference guide to anyone implementing a Spring Boot microservice
 using Kotlin and https://projects.spring.io/spring-data-cassandra/[Spring Data for Apache Cassandra] to create a CRUD repository.

It consists of a working project that can run as an independent JAR and also as a deployable WAR.

The main purpose of this example is to compare it with other Spring Data alternatives for NoSQL Databases,
 such as https://projects.spring.io/spring-data-mongodb/[Spring Data MongoDB].
 We provide an https://github.com/alexpensato/spring-boot-repositories-samples/tree/master/spring-data-mongodb-sample[example here]
 based on Spring Data MongoDB and Kotlin.

== Requirements
* JDK 1.8+
* Apache Cassandra 3.x
* Gradle 4.2.x
* An IDE that supports Kotlin language (preferably IntelliJ IDEA)

== Database preparation

Before running the project, it is necessary to create its keyspace and tables in Cassandra.

The project has a few settings configured in application.properties file, but you can modify them as you wish.

Below are CQL commands for this project:

[source, cql]
----
CREATE KEYSPACE "pensato_sample"
WITH REPLICATION  = {'class': 'SimpleStrategy',
'replication_factor': 1 };

USE pensato_sample;

CREATE TABLE college (
    name text PRIMARY KEY,
    city text,
    disciplines set<text>);

CREATE TABLE student (
    name text PRIMARY KEY,
    college text,
    enrollment timestamp);
----

== Disclaimer

This project is neither an API modeling example, nor it is as a DDD (Domain Driven Design) example.

Use it only as a Kotlin language reference guide to implement a Spring Data for Apache Cassandra microservice project.


== Contributions

…are always welcome.

Don’t hesitate to submit a https://github.com/alexpensato/spring-boot-repositories-samples/issues[bug report] or a
https://github.com/alexpensato/spring-boot-repositories-samples/pulls[pull requests].

When filling a bug report or submitting a new feature, please try including supporting test cases.


== License

This project is licensed under http://www.apache.org/licenses/LICENSE-2.0.html[Apache License 2.0].
